package fi.uba.ar.fallas.inferencia;
dialect  "mvel"

rule "Nevo Comun"
    when
        mole:Mole (shape == 'Simetrica' , border == "Regular" , diameter , ! itch)

    then
        mole.print("Nevo Comun");
end

rule "Lentigo Solar"
    when
        mole:Mole (shape == 'Asimetrica' , border == "Irregular" , ! relieve, solarExposure , ! itch)

    then
        mole.print("Lentigo Solar");
end

rule "Queratosis seborreica"
    when
        mole:Mole (shape == 'Asimetrica' , border == "Regular" , changes , relieve, solarExposure)

    then
        mole.print("Queratosis seborreica");
end

rule "Melanoma maligno"
    when
        mole:Mole (shape == 'Asimetrica' , border == "Irregular" , color == "Variado" , ! diameter, changes)

    then
        mole.print("Melanoma maligno");
end